name: stevecoxinc.net
favicon: null
layout_spectrum: 0.06948631769046187
typography_spectrum: 0.6578274320345372
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5435550154652447
  lightness: 0.3619447003584355
  saturation: 0.9002724143210799
  rhythmicContrast: 0.9416099824011326
purpose: []
